variables:
  repository: "jannemattila/azure-powershell-job"

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/*

name: 1.0.$(Rev:r)
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "DockerHub"
              repository: $(repository)
              command: "buildAndPush"
              arguments: --build-arg BUILD_VERSION=$(Build.BuildNumber)
              Dockerfile: "**/Dockerfile"
              tags: |
                $(Build.BuildNumber)
                latest
